//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.28 at 11:27:56 PM MSK 
//


package com.heim.models.server;

import com.heim.models.xmpp_stanzas.Text;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:ietf:params:xml:ns:xmpp-stanzas}stanzaErrorGroup"/>
 *         &lt;element ref="{urn:ietf:params:xml:ns:xmpp-stanzas}text" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="by" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="auth"/>
 *             &lt;enumeration value="cancel"/>
 *             &lt;enumeration value="continue"/>
 *             &lt;enumeration value="modify"/>
 *             &lt;enumeration value="wait"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "badRequest",
        "conflict",
        "featureNotImplemented",
        "forbidden",
        "gone",
        "internalServerError",
        "itemNotFound",
        "jidMalformed",
        "notAcceptable",
        "notAuthorized",
        "notAllowed",
        "paymentRequired",
        "policyViolation",
        "recipientUnavailable",
        "redirect",
        "registrationRequired",
        "remoteServerNotFound",
        "remoteServerTimeout",
        "resourceConstraint",
        "serviceUnavailable",
        "subscriptionRequired",
        "undefinedCondition",
        "unexpectedRequest",
        "text"
})
@XmlRootElement(name = "error")
public class Error {

    @XmlElement(name = "bad-request", namespace = "urn:ietf:params:xml:ns:xmpp-stanzas")
    protected String badRequest;
    @XmlElement(namespace = "urn:ietf:params:xml:ns:xmpp-stanzas")
    protected String conflict;
    @XmlElement(name = "feature-not-implemented", namespace = "urn:ietf:params:xml:ns:xmpp-stanzas")
    protected String featureNotImplemented;
    @XmlElement(namespace = "urn:ietf:params:xml:ns:xmpp-stanzas")
    protected String forbidden;
    @XmlElement(namespace = "urn:ietf:params:xml:ns:xmpp-stanzas")
    protected String gone;
    @XmlElement(name = "internal-server-error", namespace = "urn:ietf:params:xml:ns:xmpp-stanzas")
    protected String internalServerError;
    @XmlElement(name = "item-not-found", namespace = "urn:ietf:params:xml:ns:xmpp-stanzas")
    protected String itemNotFound;
    @XmlElement(name = "jid-malformed", namespace = "urn:ietf:params:xml:ns:xmpp-stanzas")
    protected String jidMalformed;
    @XmlElement(name = "not-acceptable", namespace = "urn:ietf:params:xml:ns:xmpp-stanzas")
    protected String notAcceptable;
    @XmlElement(name = "not-authorized", namespace = "urn:ietf:params:xml:ns:xmpp-stanzas")
    protected String notAuthorized;
    @XmlElement(name = "not-allowed", namespace = "urn:ietf:params:xml:ns:xmpp-stanzas")
    protected String notAllowed;
    @XmlElement(name = "payment-required", namespace = "urn:ietf:params:xml:ns:xmpp-stanzas")
    protected String paymentRequired;
    @XmlElement(name = "policy-violation", namespace = "urn:ietf:params:xml:ns:xmpp-stanzas")
    protected String policyViolation;
    @XmlElement(name = "recipient-unavailable", namespace = "urn:ietf:params:xml:ns:xmpp-stanzas")
    protected String recipientUnavailable;
    @XmlElement(namespace = "urn:ietf:params:xml:ns:xmpp-stanzas")
    protected String redirect;
    @XmlElement(name = "registration-required", namespace = "urn:ietf:params:xml:ns:xmpp-stanzas")
    protected String registrationRequired;
    @XmlElement(name = "remote-server-not-found", namespace = "urn:ietf:params:xml:ns:xmpp-stanzas")
    protected String remoteServerNotFound;
    @XmlElement(name = "remote-server-timeout", namespace = "urn:ietf:params:xml:ns:xmpp-stanzas")
    protected String remoteServerTimeout;
    @XmlElement(name = "resource-constraint", namespace = "urn:ietf:params:xml:ns:xmpp-stanzas")
    protected String resourceConstraint;
    @XmlElement(name = "service-unavailable", namespace = "urn:ietf:params:xml:ns:xmpp-stanzas")
    protected String serviceUnavailable;
    @XmlElement(name = "subscription-required", namespace = "urn:ietf:params:xml:ns:xmpp-stanzas")
    protected String subscriptionRequired;
    @XmlElement(name = "undefined-condition", namespace = "urn:ietf:params:xml:ns:xmpp-stanzas")
    protected String undefinedCondition;
    @XmlElement(name = "unexpected-request", namespace = "urn:ietf:params:xml:ns:xmpp-stanzas")
    protected String unexpectedRequest;
    @XmlElement(namespace = "urn:ietf:params:xml:ns:xmpp-stanzas")
    protected Text text;
    @XmlAttribute(name = "by")
    protected String by;
    @XmlAttribute(name = "type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;

    /**
     * Gets the value of the badRequest property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBadRequest() {
        return badRequest;
    }

    /**
     * Sets the value of the badRequest property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBadRequest(String value) {
        this.badRequest = value;
    }

    /**
     * Gets the value of the conflict property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getConflict() {
        return conflict;
    }

    /**
     * Sets the value of the conflict property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setConflict(String value) {
        this.conflict = value;
    }

    /**
     * Gets the value of the featureNotImplemented property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFeatureNotImplemented() {
        return featureNotImplemented;
    }

    /**
     * Sets the value of the featureNotImplemented property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFeatureNotImplemented(String value) {
        this.featureNotImplemented = value;
    }

    /**
     * Gets the value of the forbidden property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getForbidden() {
        return forbidden;
    }

    /**
     * Sets the value of the forbidden property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setForbidden(String value) {
        this.forbidden = value;
    }

    /**
     * Gets the value of the gone property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getGone() {
        return gone;
    }

    /**
     * Sets the value of the gone property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setGone(String value) {
        this.gone = value;
    }

    /**
     * Gets the value of the internalServerError property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getInternalServerError() {
        return internalServerError;
    }

    /**
     * Sets the value of the internalServerError property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setInternalServerError(String value) {
        this.internalServerError = value;
    }

    /**
     * Gets the value of the itemNotFound property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getItemNotFound() {
        return itemNotFound;
    }

    /**
     * Sets the value of the itemNotFound property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setItemNotFound(String value) {
        this.itemNotFound = value;
    }

    /**
     * Gets the value of the jidMalformed property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getJidMalformed() {
        return jidMalformed;
    }

    /**
     * Sets the value of the jidMalformed property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setJidMalformed(String value) {
        this.jidMalformed = value;
    }

    /**
     * Gets the value of the notAcceptable property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getNotAcceptable() {
        return notAcceptable;
    }

    /**
     * Sets the value of the notAcceptable property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setNotAcceptable(String value) {
        this.notAcceptable = value;
    }

    /**
     * Gets the value of the notAuthorized property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getNotAuthorized() {
        return notAuthorized;
    }

    /**
     * Sets the value of the notAuthorized property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setNotAuthorized(String value) {
        this.notAuthorized = value;
    }

    /**
     * Gets the value of the notAllowed property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getNotAllowed() {
        return notAllowed;
    }

    /**
     * Sets the value of the notAllowed property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setNotAllowed(String value) {
        this.notAllowed = value;
    }

    /**
     * Gets the value of the paymentRequired property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPaymentRequired() {
        return paymentRequired;
    }

    /**
     * Sets the value of the paymentRequired property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPaymentRequired(String value) {
        this.paymentRequired = value;
    }

    /**
     * Gets the value of the policyViolation property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPolicyViolation() {
        return policyViolation;
    }

    /**
     * Sets the value of the policyViolation property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPolicyViolation(String value) {
        this.policyViolation = value;
    }

    /**
     * Gets the value of the recipientUnavailable property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRecipientUnavailable() {
        return recipientUnavailable;
    }

    /**
     * Sets the value of the recipientUnavailable property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRecipientUnavailable(String value) {
        this.recipientUnavailable = value;
    }

    /**
     * Gets the value of the redirect property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRedirect() {
        return redirect;
    }

    /**
     * Sets the value of the redirect property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRedirect(String value) {
        this.redirect = value;
    }

    /**
     * Gets the value of the registrationRequired property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRegistrationRequired() {
        return registrationRequired;
    }

    /**
     * Sets the value of the registrationRequired property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRegistrationRequired(String value) {
        this.registrationRequired = value;
    }

    /**
     * Gets the value of the remoteServerNotFound property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRemoteServerNotFound() {
        return remoteServerNotFound;
    }

    /**
     * Sets the value of the remoteServerNotFound property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRemoteServerNotFound(String value) {
        this.remoteServerNotFound = value;
    }

    /**
     * Gets the value of the remoteServerTimeout property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRemoteServerTimeout() {
        return remoteServerTimeout;
    }

    /**
     * Sets the value of the remoteServerTimeout property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRemoteServerTimeout(String value) {
        this.remoteServerTimeout = value;
    }

    /**
     * Gets the value of the resourceConstraint property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getResourceConstraint() {
        return resourceConstraint;
    }

    /**
     * Sets the value of the resourceConstraint property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setResourceConstraint(String value) {
        this.resourceConstraint = value;
    }

    /**
     * Gets the value of the serviceUnavailable property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getServiceUnavailable() {
        return serviceUnavailable;
    }

    /**
     * Sets the value of the serviceUnavailable property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setServiceUnavailable(String value) {
        this.serviceUnavailable = value;
    }

    /**
     * Gets the value of the subscriptionRequired property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSubscriptionRequired() {
        return subscriptionRequired;
    }

    /**
     * Sets the value of the subscriptionRequired property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSubscriptionRequired(String value) {
        this.subscriptionRequired = value;
    }

    /**
     * Gets the value of the undefinedCondition property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUndefinedCondition() {
        return undefinedCondition;
    }

    /**
     * Sets the value of the undefinedCondition property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUndefinedCondition(String value) {
        this.undefinedCondition = value;
    }

    /**
     * Gets the value of the unexpectedRequest property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUnexpectedRequest() {
        return unexpectedRequest;
    }

    /**
     * Sets the value of the unexpectedRequest property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUnexpectedRequest(String value) {
        this.unexpectedRequest = value;
    }

    /**
     * Gets the value of the text property.
     *
     * @return possible object is
     * {@link Text }
     */
    public Text getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     *
     * @param value allowed object is
     *              {@link Text }
     */
    public void setText(Text value) {
        this.text = value;
    }

    /**
     * Gets the value of the by property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBy() {
        return by;
    }

    /**
     * Sets the value of the by property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBy(String value) {
        this.by = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setType(String value) {
        this.type = value;
    }

}
