//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.28 at 11:27:56 PM MSK 
//


package com.heim.models.server;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the jabber.server package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Priority_QNAME = new QName("jabber:server", "priority");
    private final static QName _Show_QNAME = new QName("jabber:server", "show");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jabber.server
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Subject }
     */
    public Subject createSubject() {
        return new Subject();
    }

    /**
     * Create an instance of {@link Iq }
     */
    public Iq createIq() {
        return new Iq();
    }

    /**
     * Create an instance of {@link Error }
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link Thread }
     */
    public Thread createThread() {
        return new Thread();
    }

    /**
     * Create an instance of {@link Message }
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link Body }
     */
    public Body createBody() {
        return new Body();
    }

    /**
     * Create an instance of {@link Presence }
     */
    public Presence createPresence() {
        return new Presence();
    }

    /**
     * Create an instance of {@link Status }
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     */
    @XmlElementDecl(namespace = "jabber:server", name = "priority", defaultValue = "0")
    public JAXBElement<Byte> createPriority(Byte value) {
        return new JAXBElement<Byte>(_Priority_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "jabber:server", name = "show")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createShow(String value) {
        return new JAXBElement<String>(_Show_QNAME, String.class, null, value);
    }

}
