//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.28 at 08:29:22 PM MSK 
//


package com.heim.models.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="resource" type="{urn:ietf:params:xml:ns:xmpp-bind}resourceType"/>
 *         &lt;element name="jid" type="{urn:ietf:params:xml:ns:xmpp-bind}fullJIDType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "resource",
        "jid"
})
@XmlRootElement(name = "bind")
public class Bind {

    protected String resource;
    protected String jid;

    /**
     * Gets the value of the resource property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getResource() {
        return resource;
    }

    /**
     * Sets the value of the resource property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setResource(String value) {
        this.resource = value;
    }

    /**
     * Gets the value of the jid property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getJid() {
        return jid;
    }

    /**
     * Sets the value of the jid property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setJid(String value) {
        this.jid = value;
    }

}
