//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.28 at 07:27:09 PM MSK 
//


package com.heim.models.auth;


import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="aborted" type="{urn:ietf:params:xml:ns:xmpp-sasl}empty"/>
 *           &lt;element name="account-disabled" type="{urn:ietf:params:xml:ns:xmpp-sasl}empty"/>
 *           &lt;element name="credentials-expired" type="{urn:ietf:params:xml:ns:xmpp-sasl}empty"/>
 *           &lt;element name="encryption-required" type="{urn:ietf:params:xml:ns:xmpp-sasl}empty"/>
 *           &lt;element name="incorrect-encoding" type="{urn:ietf:params:xml:ns:xmpp-sasl}empty"/>
 *           &lt;element name="invalid-authzid" type="{urn:ietf:params:xml:ns:xmpp-sasl}empty"/>
 *           &lt;element name="invalid-mechanism" type="{urn:ietf:params:xml:ns:xmpp-sasl}empty"/>
 *           &lt;element name="malformed-request" type="{urn:ietf:params:xml:ns:xmpp-sasl}empty"/>
 *           &lt;element name="mechanism-too-weak" type="{urn:ietf:params:xml:ns:xmpp-sasl}empty"/>
 *           &lt;element name="not-authorized" type="{urn:ietf:params:xml:ns:xmpp-sasl}empty"/>
 *           &lt;element name="temporary-auth-failure" type="{urn:ietf:params:xml:ns:xmpp-sasl}empty"/>
 *           &lt;element name="transition-needed" type="{urn:ietf:params:xml:ns:xmpp-sasl}empty"/>
 *         &lt;/choice>
 *         &lt;element ref="{urn:ietf:params:xml:ns:xmpp-sasl}text" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "aborted",
        "accountDisabled",
        "credentialsExpired",
        "encryptionRequired",
        "incorrectEncoding",
        "invalidAuthzid",
        "invalidMechanism",
        "malformedRequest",
        "mechanismTooWeak",
        "notAuthorized",
        "temporaryAuthFailure",
        "transitionNeeded",
        "text"
})
@XmlRootElement(name = "failure")
public class Failure {

    protected String aborted;
    @XmlElement(name = "account-disabled")
    protected String accountDisabled;
    @XmlElement(name = "credentials-expired")
    protected String credentialsExpired;
    @XmlElement(name = "encryption-required")
    protected String encryptionRequired;
    @XmlElement(name = "incorrect-encoding")
    protected String incorrectEncoding;
    @XmlElement(name = "invalid-authzid")
    protected String invalidAuthzid;
    @XmlElement(name = "invalid-mechanism")
    protected String invalidMechanism;
    @XmlElement(name = "malformed-request")
    protected String malformedRequest;
    @XmlElement(name = "mechanism-too-weak")
    protected String mechanismTooWeak;
    @XmlElement(name = "not-authorized")
    protected String notAuthorized;
    @XmlElement(name = "temporary-auth-failure")
    protected String temporaryAuthFailure;
    @XmlElement(name = "transition-needed")
    protected String transitionNeeded;
    protected Text text;

    /**
     * Gets the value of the aborted property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAborted() {
        return aborted;
    }

    /**
     * Sets the value of the aborted property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAborted(String value) {
        this.aborted = value;
    }

    /**
     * Gets the value of the accountDisabled property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAccountDisabled() {
        return accountDisabled;
    }

    /**
     * Sets the value of the accountDisabled property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAccountDisabled(String value) {
        this.accountDisabled = value;
    }

    /**
     * Gets the value of the credentialsExpired property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCredentialsExpired() {
        return credentialsExpired;
    }

    /**
     * Sets the value of the credentialsExpired property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCredentialsExpired(String value) {
        this.credentialsExpired = value;
    }

    /**
     * Gets the value of the encryptionRequired property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEncryptionRequired() {
        return encryptionRequired;
    }

    /**
     * Sets the value of the encryptionRequired property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEncryptionRequired(String value) {
        this.encryptionRequired = value;
    }

    /**
     * Gets the value of the incorrectEncoding property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIncorrectEncoding() {
        return incorrectEncoding;
    }

    /**
     * Sets the value of the incorrectEncoding property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIncorrectEncoding(String value) {
        this.incorrectEncoding = value;
    }

    /**
     * Gets the value of the invalidAuthzid property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getInvalidAuthzid() {
        return invalidAuthzid;
    }

    /**
     * Sets the value of the invalidAuthzid property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setInvalidAuthzid(String value) {
        this.invalidAuthzid = value;
    }

    /**
     * Gets the value of the invalidMechanism property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getInvalidMechanism() {
        return invalidMechanism;
    }

    /**
     * Sets the value of the invalidMechanism property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setInvalidMechanism(String value) {
        this.invalidMechanism = value;
    }

    /**
     * Gets the value of the malformedRequest property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMalformedRequest() {
        return malformedRequest;
    }

    /**
     * Sets the value of the malformedRequest property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMalformedRequest(String value) {
        this.malformedRequest = value;
    }

    /**
     * Gets the value of the mechanismTooWeak property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMechanismTooWeak() {
        return mechanismTooWeak;
    }

    /**
     * Sets the value of the mechanismTooWeak property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMechanismTooWeak(String value) {
        this.mechanismTooWeak = value;
    }

    /**
     * Gets the value of the notAuthorized property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getNotAuthorized() {
        return notAuthorized;
    }

    /**
     * Sets the value of the notAuthorized property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setNotAuthorized(String value) {
        this.notAuthorized = value;
    }

    /**
     * Gets the value of the temporaryAuthFailure property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTemporaryAuthFailure() {
        return temporaryAuthFailure;
    }

    /**
     * Sets the value of the temporaryAuthFailure property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTemporaryAuthFailure(String value) {
        this.temporaryAuthFailure = value;
    }

    /**
     * Gets the value of the transitionNeeded property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTransitionNeeded() {
        return transitionNeeded;
    }

    /**
     * Sets the value of the transitionNeeded property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTransitionNeeded(String value) {
        this.transitionNeeded = value;
    }

    /**
     * Gets the value of the text property.
     *
     * @return possible object is
     * {@link Text }
     */
    public Text getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     *
     * @param value allowed object is
     *              {@link Text }
     */
    public void setText(Text value) {
        this.text = value;
    }

}
